# Schema for the configuration files of the Login Redirect module

login_redirect.settings:
  type: config_object
  label: 'Login redirect settings'
  mapping:
    status:
      type: boolean
      label: 'Module status'
    destination:
      type: string
      label: 'Destination URI'
